Optimise and improve tests on Travis
- Run setup script only once to improve performence.
- Test Ansible playbooks for syntax errors before other tests.
- Run tasks directly with ansible-playbook and test for idempotence.

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,4 +1,5 @@
 #!/bin/bash
+
 if test "$(uname)" = "Darwin"; then
   if test ! $(which gcc); then
     echo "Installing xcode..."
@@ -37,7 +38,14 @@ fi
 
 python --version
 ansible --version
-ansible-galaxy install -r requirements.yml -p roles
+ansible-galaxy install -r requirements.yml -p roles || { echo "Failed to install Ansible roles"; exit 1; }
+
+if [[ "$1" == "--skip-playbook" ]]; then
+  echo "Skipping Ansible playbook execution"
+  shift
+  exit 0
+fi
+
 ansible-playbook main.yml $@
 
 # I don't have a bootstrap script for my dotfiles
